### ISSUE TITLE
Ubuntu and cogroo4py.jar 

### ISSUE THREAD

**Issue by itsbarreto** [gpassero/cogroo4py#1]
Hi everyone,

In Ubuntu 18.4 LTS when I execute the command: `java -jar cogroo4py.jar`
The system returns
Exception in thread "main" java.lang.NoClassDefFoundError: org/cogroo/text/Document
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:374)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
Caused by: java.lang.ClassNotFoundException: org.cogroo.text.Document
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 3 more
Somebody can help me?

**Comment by gpassero** [comment]
Hi @itsbarreto,
I just clean installed Ubuntu 18.04LTS in a virtual machine, installed openjdk-8 and python3, then cloned this repo. I could execute the command `java -jar cogroo4py.jar` without having issues.
Can you please check your java version with `java -version` (should be 1.8+). Also, check if there is another version of cogroo in your java classpath (check $CLASSPATH env variable) and make sure you are using the [latest version of cogroo4py.jar](https://github.com/gpassero/cogroo4py/blob/master/cogroo4py.jar?raw=true) (oct-2016).

**Comment by gpassero** [comment]
Hi @itsbarreto . Can you please try again using Java v. 1.8? I found that `cogroo4py.jar` does not work with Java 1.10, probably does not work with 1.9 either.

**Comment by gpassero** [comment]
As I've mentioned in the last comment, I've found this library to work only with JRE 1.8. The README was updated regarding this limitation.
Considering there's an easy workaround, and I still have not found an easy solution to make this work with JRE 1.9+, I'm closing this issue. I'll reopen it if it gets some thumbs up. 😃

**Comment by bianca-flores** [comment]
Hey! @gpassero, I'm having the exact same issue as our friend above and I'm kind of new to this, so didn't quite understand your explanation. Could you try and help me? 

I ran the java -version command as you suggested and got a weird output with the description of my JDK instead: 

````
Successfully built cogroo-interface

bianca_flores@Biancas-MacBook-Pro cogroo4py-master %  java -jar cogroo4py.jar

Exception in thread "main" java.lang.NoClassDefFoundError: org/cogroo/text/Document
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
Caused by: java.lang.ClassNotFoundException: org.cogroo.text.Document
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 3 more`

bianca_flores@Biancas-MacBook-Pro cogroo4py-master % java -version 
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)
````

**Comment by gpassero** [comment]
Hi @bianca-flores! Based on the outputs you shared, I can see that your Java Runtime version is 11 (`java -version` yields `11.0.8`). Unfortunately, cogroo4py.jar doesn't work with Java 11. Can you please try again by running cogroo4py.jar with Java 8?
  I understand Java 11 is the most popular version nowadays and it is annoying we can't use it to run cogroo4py.jar. The cogroo project is [currently designed to run with Java 8](https://github.com/cogroo/cogroo4/blob/master/pom.xml#L156), there is [an open issue](https://github.com/cogroo/cogroo4/issues/28) to update it to Java 11.
